### ISSUE TITLE
application_name is not set for each connection

### ISSUE THREAD

**Issue by mayli** [level12/pals#24]
It would be cool if we can use https://github.com/level12/pals/blob/master/pals/core.py#L51 as the connecition name, but it's not being used in the connection.

**Comment by rsyring** [comment]
Which "connection name" are you referring to?

**Comment by mayli** [comment]
I've made a quick and dirty hack in this commit: https://github.com/mayli/pals/commit/f978516109bf88398ee89cf8973fcf4f585130cb

**Comment by rsyring** [comment]
I understand now, thanks.  I don't think that is something PALS needs to support as you can do that at the SQLAlchemy connection level.  Adjusting your db URL or using a custom engine should be sufficient.

Please see [this SO answer](https://stackoverflow.com/a/15691283) for an example.
