### ISSUE TITLE
Prepare for SQLAlchemy 2.0

### ISSUE THREAD

**Issue by bchopson** [level12/pals#38]
See https://docs.sqlalchemy.org/en/14/changelog/migration_20.html

**Comment by maciejstromich** [comment]
PALs is not restricting version of SQLAlchemy to be <= than 1.4.44 which means that right now after sqlalchemy 2.0 was released during installation pip chooses version 2.0 and then acquire fails with 
```
builtins:AttributeError 'Connection' object has no attribute 'connect'
```

**Comment by rsyring** [comment]
Should be an easy change.  Can also just set it to `< 2.0` I believe.

**Comment by maciejstromich** [comment]
I guess so. I've mentioned 1.4.44 as it's the version that was previously installed in our systems but later I saw that there's already 1.4.47 in the changelog docs.
