### ISSUE TITLE
feature: default kwargs for locks

### ISSUE THREAD

**Issue by jeffb4** [level12/pals#5]
It would be neat to have a `default_lock_params` argument to `Locker` to allow things like `blocking=False` without needing to remember to do so for every `.lock()` call.

Thanks for creating this library, it works really really well.

**Comment by rsyring** [comment]
Agreed, although I think the API I would prefer would probably be something like:

```python
class Locker:
    def __init__(self, app_name, blocking_default=True, aquire_timeout_default=1000, create_engine_args=None, create_engine_kwargs=None):
```

This would be a BC break due to the change of how *args and **kwargs was handled, but this seems more explicit to me and explicit is better than implicit.
